from enum import Enum


class StyledImageThemeEnum(str, Enum):
    """Enum containing the allowed themes."""

    AFREMOV_SLEEPING_CITY = "afremov-sleeping-city"
    ARM_OF_THE_SEINE = "arm-of-the-seine"
    BETZLER_RECLINING_COUPLE = "betzler-reclining-couple"
    CAFE_TERRACE_AT_NIGHT = "cafe-terrace-at-night"
    CARAVAGGIO = "caravaggio"
    CARAVAGGIO_SELF_PORTRAIT = "caravaggio-self-portrait"
    CLAUDE_MONET = "claude-monet"
    DA_VINCI = "da-vinci"
    GARDEN_AT_GIVERNY = "garden-at-giverny"
    GIRL_BEFORE_A_MIRROR = "girl-before-a-mirror"
    GIRL_IN_WHITE = "girl-in-white"
    GIRL_WITH_A_MANDOLIN = "girl-with-a-mandolin"
    HAMILTON_FASHION_PLATE = "hamilton-fashion-plate"
    KIRCHNER_SERTIGTAL_IN_AUTUMN = "kirchner-sertigtal-in-autumn"
    KLIMT_HYGIEIA = "klimt-hygieia"
    KLIMT_THE_KISS = "klimt-the-kiss"
    LES_FEMMES_DALGIERS = "les-femmes-dalgiers"
    MONA_LISA = "mona-lisa"
    MUCHA_DAYDREAM = "mucha-daydream"
    MUCHA_LA_PLUME = "mucha-la-plume"
    MUNCH_THE_SCREAM = "munch-the-scream"
    PECHSTEIN_LEBA_HARBOUR = "pechstein-leba-harbour"
    PENITENT_MAGDELENE = "penitent-magdelene"
    PICASSO = "picasso"
    PISSARRO_MIRIBEAU_GARDEN = "pissarro-miribeau-garden"
    RAUSCHENBERG_RETROACTIVE = "rauschenberg-retroactive"
    REMBRANDT = "rembrandt"
    REMBRANDT_SELF_PORTRAIT = "rembrandt-self-portrait"
    RENOIR_GIRLS_AT_THE_PIANO = "renoir-girls-at-the-piano"
    ROESTENBURG_EIFEL_SUMMER = "roestenburg-eifel-summer"
    SARGENT_IN_A_LEVANTINE_PORT = "sargent-in-a-levantine-port"
    STARRY_NIGHT = "starry-night"
    SUNSET_RED_AND_GOLD = "sunset-red-and-gold"
    THE_BALCONY = "the-balcony"
    THE_CROWNING_WITH_THORNS = "the-crowning-with-thorns"
    THE_ENTOMBMENT_OF_CHRIST = "the-entombment-of-christ"
    THE_GENTLE_ART_OF_MAKING_ENEMIES = "the-gentle-art-of-making-enemies"
    THE_NIGHT_WATCH = "the-night-watch"
    THE_STORM = "the-storm"
    THE_WEEPING_WOMAN = "the-weeping-woman"
    TOBIAS_AND_THE_ANGEL = "tobias-and-the-angel"
    VAN_GOGH = "van-gogh"
    VAN_GOGH_SELF_PORTRAIT = "van-gogh-self-portrait"
    VIRGIN_OF_THE_ROCKS = "virgin-of-the-rocks"
    VITRUVIAN_MAN = "vitruvian-man"
    WAIN_KALEIDOSCOPE_CAT = "wain-kaleidoscope-cat"
    WARHOL_MARILYN = "warhol-marilyn"
    WATER_LILLIES = "water-lillies"
    WHEAT_FIELD = "wheat-field"
    WHISTLER = "whistler"
    WINTER_LANDSCAPE = "winter-landscape"
    WOMAN_WITH_A_PARASOL = "woman-with-a-parasol"
